In [ ]:
import pandas as pd
import numpy as np

In [ ]:
train = pd.read_csv('/content/train.csv')
test = pd.read_csv('/content/test.csv')

In [ ]:
train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [ ]:
train['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [ ]:
def transformar_sexo(valor):
  if valor == 'female':
    return 1
  else:
    return 0

train['Sex_binario'] = train['Sex'].map(transformar_sexo)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [ ]:
#?train_test_split

In [ ]:
#variaveis prioritárias no resgate, mulheres e crianças
variaveis = ['Sex_binario', 'Age']

In [ ]:
X = train[variaveis]
y = train['Survived']

In [ ]:
X = X.fillna(-1)

In [ ]:
X_falso = np.arange(10)
X_falso

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.seed(0)
train_test_split(X_falso)

[array([9, 1, 6, 7, 3, 0, 5]), array([2, 8, 4])]

In [25]:
np.random.seed(1)
X_treino, X_valid, y_treino, y_valid = train_test_split(X, y, test_size=0.5)

In [26]:
X_treino

Sex_binario    Age
394            1  24.00
851            0  74.00
373            0  22.00
523            1  44.00
78             0   0.83
..           ...    ...
715            0  19.00
767            1  30.50
72             0  21.00
235            1  -1.00
37             0  21.00

[445 rows x 2 columns]

In [27]:
modelo = RandomForestClassifier(n_estimators=100, n_jobs=1, random_state=1)

In [28]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Sex_binario  
0      0         A/5 21171   7.2500   NaN        S            0  
1      0          PC 17599  71.2833   C85        C            1  
2      0  STON/O2. 3101282   7.9250   NaN        S            1  
3      0            113803  53.1000  C123        S            1  
4      0            373450   8.0500   NaN        S            0

In [29]:
X.head()

Sex_binario   Age
0            0  22.0
1            1  38.0
2            1  26.0
3            1  35.0
4            0  35.0

In [30]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [31]:
modelo.fit(X_treino, y_treino)

RandomForestClassifier(n_jobs=1, random_state=1)

In [32]:
modelo.fit(X_treino, y_treino)

RandomForestClassifier(n_jobs=1, random_state=1)

In [33]:
p = modelo.predict(X_valid)
p

array([1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,

In [34]:
np.mean(y_valid == p)

0.7466367713004485

In [35]:
p = (X_valid['Sex_binario'] == 1).astype(np.int64)
np.mean(y_valid == p)

0.7623318385650224

# Validacao Cruzada

In [36]:
X_falso

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
from sklearn.model_selection import KFold

In [39]:
kf = KFold(2, shuffle=True, random_state=0)
for linhastreino, linhastest in kf.split(X_falso):
  print('treino', linhastreino)
  print('validacao', linhastest)

treino [0 3 5 6 7]
validacao [1 2 4 8 9]
treino [1 2 4 8 9]
validacao [0 3 5 6 7]


In [43]:
resultados = []

for c in range(10):
  kf = KFold(2, shuffle=True, random_state=0)
  for linhas_treino, linhas_valid in kf.split(X):
    print('treino', linhas_treino.shape[0])
    print('validacao', linhas_valid.shape[0])
    print()

    X_treino, X_valid = X.iloc[linhas_treino], X.iloc[linhas_valid]
    y_treino, y_valid = y.iloc[linhas_treino], y.iloc[linhas_valid]


    modelo = RandomForestClassifier(n_estimators=100, random_state=0, n_jobs=1)
    modelo.fit(X_treino, y_treino)

    p = modelo.predict(X_valid)

    acc = np.mean(y_valid == p)
    resultados.append(acc)
    print("acc", acc)
    print()


  #print(X_treino.head())
  #print()

treino 445
validacao 446

acc 0.7713004484304933

treino 446
validacao 445

acc 0.7797752808988764

treino 445
validacao 446

acc 0.7713004484304933

treino 446
validacao 445

acc 0.7797752808988764

treino 445
validacao 446

acc 0.7713004484304933

treino 446
validacao 445

acc 0.7797752808988764

treino 445
validacao 446

acc 0.7713004484304933

treino 446
validacao 445

acc 0.7797752808988764

treino 445
validacao 446

acc 0.7713004484304933

treino 446
validacao 445

acc 0.7797752808988764

treino 445
validacao 446

acc 0.7713004484304933

treino 446
validacao 445

acc 0.7797752808988764

treino 445
validacao 446

acc 0.7713004484304933

treino 446
validacao 445

acc 0.7797752808988764

treino 445
validacao 446

acc 0.7713004484304933

treino 446
validacao 445

acc 0.7797752808988764

treino 445
validacao 446

acc 0.7713004484304933

treino 446
validacao 445

acc 0.7797752808988764

treino 445
validacao 446

acc 0.7713004484304933

treino 446
validacao 445

acc 0.7797752808988764



In [44]:
resultados

[0.7713004484304933,
 0.7797752808988764,
 0.7713004484304933,
 0.7797752808988764,
 0.7713004484304933,
 0.7797752808988764,
 0.7713004484304933,
 0.7797752808988764,
 0.7713004484304933,
 0.7797752808988764,
 0.7713004484304933,
 0.7797752808988764,
 0.7713004484304933,
 0.7797752808988764,
 0.7713004484304933,
 0.7797752808988764,
 0.7713004484304933,
 0.7797752808988764,
 0.7713004484304933,
 0.7797752808988764]

In [47]:
np.mean(resultados)

0.7755378646646849